SELECT
	LISTING_ID,
	HOST_ID,
	REVIEW_COUNT,
	OVERALL_RATING,
	ACCURACY_RATING,
	CHECKIN_RATING,
	CLEANLINESS_RATING,
	COMMUNICATION_RATING,
	VALUE_RATING,
	VALID_FROM,
	VALID_TO
		FROM {{ ref('fact_listings') }}
